### PR TITLE
updated the design

### PR DESCRIPTION
**Pull request by Sushie611**
Dear Sir ,
            I have updated the design view of the library management system 
[lms.zip](https://github.com/prafullpandey614/HactoberFest-2022/files/9689304/lms.zip)

### CODE REVIEW

**Comment by prafullpandey614** [comment]
Sure @Sushie611 
I am going to merge it 
🙂

**Comment by Sushie611** [comment]
thank you so much sir

**Comment by Sushie611** [comment]
sir why is it showing excluded by hacktober fest

**Comment by prafullpandey614** [comment]
Hey @Sushie611  the problem is that you added a image file only and that in contributors.md it is against the rule of Hactoberfest 
You should write some code and then Make a PR 
It was also a big mistake from my side that i given you label.of hactoberfest accepted without seeing the code change
Hope you understand and try to enhance the project like you can add html files with some decoration

**Pull request merged**
